config/routes.rb
Personalwebsite::Application.routes.draw do 
  devise_for :admins, :skip => :registrations
  root 'posts#index'
  get 'manage' => 'manage#index' 

  get 'posts/category/:category' => 'posts#index', 
    constraints: { category: /programming|personal/ }
  get 'posts/tag/:tag' => 'posts#index'

  get 'resume' => 'resume#index'
  get 'contact' => 'contact#index'

  resources :posts do
    resources :comments
  end

  resources :tags, only: [:index, :new, :create, :destroy] 
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules :registerable, :recoverable, 
  # :rememberable, :trackable, :validatable
  # Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :tags

  validates :title, presence: true
  validates :body, presence: true
  validates :posted, presence: true
  validates :category_id, presence: true

  extend FriendlyId
  friendly_id :title, :use => :slugged
end

app/models/resume.rb
class Resume
  require 'yaml'

  def self.get_programming_experience
    get_yaml_data 'qualifications.yml', 'Unable to load programming experience.'
  end

  def self.get_employment_history
    get_yaml_data 'employment_history.yml', 'Unable to load employment history.'
  end
  
  def self.get_education
    get_yaml_data 'education.yml', 'Unable to load education.'
  end

  def self.get_extras
    get_yaml_data 'extras.yml', 'Unable to load extras.'
  end

  private 
  def self.get_yaml_data(file, error_message)
    begin
      YAML.load_file(Rails.root.join('data', file))
    rescue
      Array.new([error_message])
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, presence: true, uniqueness: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @all_posts = Post.all.order(posted: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  before_action :authenticate_admin!

  def index
    @all_posts = Post.all.order(posted: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    if params[:category]
      @posts = Category.find_by_name(params[:category].capitalize).posts
    elsif params[:tag]
      @posts = Tag.find_by_name(params[:tag]).posts
    else
      @posts = Post.all
    end
    @posts = @posts.order(created_at: :desc).page params[:page]
  end

  def show
    @post = Post.friendly.find params[:id]
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post '#{@post.title}' was successfully saved."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.friendly.find params[:id]
    @tags = Tag.all
  end

  def update
    @post = Post.friendly.find params[:id]
    if @post.update_attributes(post_params)
      flash[:notice] = "Post '#{@post.title}' was successfully updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find params[:id]
    @post.destroy
    flash[:notice] = "Post '#{@post.title}' was successfuly destroyed."
    redirect_to manage_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :posted, :category_id, tag_ids: [])
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
    @programming_experience = Resume.get_programming_experience
    @employment_history = Resume.get_employment_history
    @education = Resume.get_education
    @extras = Resume.get_extras
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag '#{@tag.name}' was successfully created."
    end
    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find params[:id]
    @tag.destroy
    flash[:notice] = "Tag '#{@tag.name}' was successfully destroyed."
    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
require 'redcarpet'
require 'pygmentize'

module MarkdownHelper
  def markdown_with_pygmentize(text)
    options = {fenced_code_blocks: true, disable_indented_code_blocks: true,
      no_intra_emphasis: true}
    redcarpet = Redcarpet::Markdown.new(PygmentizeHTML, options)
    redcarpet.render(text).html_safe
  end

  class PygmentizeHTML < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygmentize.process(code, language)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def formatted_post_date(date)
    date.strftime("%B, %-d, %Y")
  end

  def formatted_tag_list(tags)
    tags.map { |tag| link_to tag.name, "/posts/tag/#{tag.name}" }
        .join(", ").html_safe
  end

  def truncated_post_body(body)
    truncate(body.split(/```|~~~|\r|\n/).first, :length => 400)
  end
end

app/helpers/social_media_links_helper.rb
module SocialMediaLinksHelper
  def twitter_link
    'https://twitter.com/carlhinderer'
  end

  def github_link
    'https://github.com/carlhinderer'
  end

  def linkedin_link
    'http://www.linkedin.com/in/carlhinderer'
  end

  def facebook_link
    'https://www.facebook.com/carl.hinderer.16'
  end

  def googleplus_link
    'https://plus.google.com/110122098344025416472/about'
  end
end

app/views/admins/index.html.haml
%h3 Admin Page

%table.post_admin_table
  %tr
    %th Title
    %th Created On
    %th Edit
    %th Delete
  - @all_posts.each do |post|
    %tr
      %td= post.title
      %td= post.posted
      %td= link_to "Edit", edit_post_path(post)
      %td= link_to "Delete", post_path(post), :method => :delete,
        :confirm => "Are you sure you want to delete the post '#{post.title}'?"

= link_to 'Add new post', new_post_path, {class: 'new_post_link'}

app/views/application/_footer.html.haml
Copyright &copy; 2014 www.carlhinderer.net.  
%br
This site uses #{link_to 'Glyphicons', 'http://glyphicons.com'}.

app/views/application/_message_bar.html.haml
-if flash[:notice]
  #notice.message= flash[:notice]
-elsif flash[:warning]
  #notice.warning= flash[:warning]

app/views/application/_navigation_bar.html.haml
%nav.navbar-default.navbar-fixed-top{role: 'navigation'}
  .container-fluid
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Carl Hinderer's Blog", root_url, {class: 'navbar-brand'}
        %li= link_to 'Programming Blog', '/posts/category/programming', {class: 'navbar_option'}
        %li= link_to 'Personal Blog', '/posts/category/personal', {class: 'navbar_option' }
        %li= link_to 'Resume', resume_path, {class: 'navbar_option'}
        %li= link_to 'Contact', contact_path, {class: 'navbar_option'}
      %ul.nav.navbar-nav.navbar-right
        %li= link_to image_tag('navbar/twitter.png'), twitter_link, {class: 'social_media_link'}
        %li= link_to image_tag('navbar/github.png'), github_link, {class: 'social_media_link'}
        %li= link_to image_tag('navbar/linked_in.png'), linkedin_link, {class: 'social_media_link'}
        %li= link_to image_tag('navbar/facebook.png'), facebook_link, {class: 'social_media_link'}
        %li= link_to image_tag('navbar/google_plus.png'), googleplus_link, {class: 'social_media_link'}

app/views/contact/index.html.haml
#contact_info
  %p Contact me at #{mail_to 'carl.hinderer4@gmail.com', 'carl.hinderer4@gmail.com'}
  %p Or connect with me at one of these fine social networking sites:
  %ul.contact_links
    %li= link_to image_tag('contact/Twitter_logo_blue.png'), twitter_link
    %li= link_to image_tag('contact/Octocat.png'), github_link
    %li= link_to image_tag('contact/LinkedIn-InBug.png'), linkedin_link
    %li= link_to image_tag('contact/FB-50.png'), facebook_link
    %li= link_to image_tag('contact/g+64.png'), googleplus_link

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title #{@title || 'Carl Hinderer\'s Blog'}
    = stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true
    = javascript_include_tag 'application', "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    #wrap
      .container
        = render :partial => 'navigation_bar'
        = render :partial => 'message_bar'
        .row
          .col-md-2
          .col-md-8
            =yield
          .col-md-2
      #push
        
    #footer
      .container
        = render :partial => 'footer'

app/views/posts/_disqus_thread.html.haml
#disqus_thread
  :javascript
    var disqus_shortname = 'carlhinderersblog'; 

    (function() {
      var dsq = document.createElement('script'); 
      dsq.type = 'text/javascript'; 
      dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).
        appendChild(dsq);
    })();

  %noscript
    = 'Please enable Javascript to enable the '
    = link_to 'comments powered by Disqus.', 'http://disqus.com/?ref_noscript'

  = link_to 'http://disqus.com', {class: 'dsq-brlink'} do
    = 'Blog comments powered by '
    %span{class: 'logo-disqus'}= 'Disqus'

app/views/posts/_post_form.html.haml
- unless @post.errors.empty?
  #warning
    Errors prevented this post from being #{controller.action_name}d.
    %ul
      - @post.errors.full_messages.each do |error|
        %li= error

.form-group
  = label :post, :title, 'Title'
  = text_field :post, :title, :size => 70, class: 'form-control'
.form-group
  = label :post, :body, 'Body'
  = text_area :post, :body, :cols => 100, :rows => 30, class: 'form-control'
.form-group
  = label :post, :posted, 'Date Posted'
  %br
  = date_select :post, :posted
.form-group
  = label :post, :category_id, 'Category'
  %br
  = select :post, :category_id, [['Programming', 1], ['Personal', 2]]
.form-group
  = label :post, :tags, 'Tags'
  - if @tags
    - @tags.each do |tag|
      .checkbox
        = tag.name
        = hidden_field_tag "post[tag_ids][]"
        = check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag), 
          :id => "post_tag_ids_#{tag.id}"

app/views/posts/_post_summaries.html.haml
#posts
  -if @posts.any?
    = render :partial => 'post_summary', :collection => @posts, :as => :post
    = paginate @posts
  -else
    %p= 'Posts coming soon.'

app/views/posts/_post_summary.html.haml
%div[post]
  .post_summary_date_tags Posted #{formatted_post_date(post.posted)} on #{formatted_tag_list(post.tags)}
  .post_summary_title= link_to("#{post.title}", "/posts/#{post.slug}")
  .post_summary_body= markdown_with_pygmentize(truncated_post_body(post.body))
  %hr.post-summary-separator

app/views/posts/edit.html.haml
%h2 Edit Post

= form_tag post_path(@post), :method => :put do
  = render :partial => 'post_form'
  = submit_tag 'Save Changes'

app/views/posts/index.html.haml
= render :partial => 'post_summaries'

app/views/posts/new.html.haml
%h2 Create New Post

= form_tag posts_path, :method => :post do
  = render :partial => 'post_form'
  = submit_tag 'Create Post'

app/views/posts/show.html.haml
- @title = @post.title
#post
  .date_tags Posted #{formatted_post_date(@post.posted)} on #{formatted_tag_list(@post.tags)} 
  .title= @post.title
  .body= find_and_preserve markdown_with_pygmentize(@post.body)
  = render :partial => 'disqus_thread'

app/views/resume/_accordion_panel.html.haml
.panel-heading
  %h4.panel-title
    = link_to panel_title, "#collapse#{panel_number}", 
      'data-toggle' => 'collapse', 
      'data-parent' => '#accordion'
.panel-collapse.collapse{id: "collapse#{panel_number}"}
  .panel-body
    = panel_content

app/views/resume/_education.html.haml
- @education.each do |degree, degree_details|
  %p.resume_category_title= degree
  %p.resume_institution= degree_details["school"]
  %p= "#{degree_details["dates"]} | #{degree_details["location"]}"
  %ul.resume_category_list

app/views/resume/_employment_history.html.haml
- @employment_history.each do |job_title, job_details|
  %p.resume_category_title= job_title.titleize
  %p.resume_institution= job_details["company"]
  %p.resume_dates #{job_details["dates"]} | #{job_details["location"]}
  %ul.resume_category_list
    - job_details["duties"].each do |duty|
      %li= duty

app/views/resume/_extras.html.haml
- @extras.each do |name, extras|
  %p.resume_category_title= name
  %ul.resume_category_list
    -extras.each do |extra|
      %li= extra

app/views/resume/_programming_experience.html.haml
- @programming_experience.each do |category, qualifications|
  %p.resume_category_title= category.titleize
  %ul.resume_category_list
    - qualifications.each do |qualification|
      %li= qualification

app/views/resume/index.html.haml
%h2.resume_title My Current Resume

.panel-group{id: 'accordion'}
  .panel.panel-default
    = render :partial => 'accordion_panel', :locals => {panel_title: 'Programming Experience', 
      panel_number: 1,
      panel_content: render(:partial => 'programming_experience')}

    = render :partial => 'accordion_panel', :locals => {panel_title: 'Work Experience',
      panel_number: 2,
      panel_content: render(:partial => 'employment_history')}

    = render :partial => 'accordion_panel', :locals => {panel_title: 'Education',
      panel_number: 3,
      panel_content: render(:partial => 'education')}

    = render :partial => 'accordion_panel', :locals => {panel_title: 'Extra Stuff',
      panel_number: 4,
      panel_content: render(:partial => 'extras')}

app/views/tags/index.html.haml
%h3 Manage Tags

%table.admin_table
  %tr
    %th Name
    %th Delete
  - @tags.each do |tag|
    %tr
      %td= tag.name
      %td= link_to('Delete', tag_path(tag), :method => :delete)

%h4 Add New Tag
= form_for :tag, :url => {:controller => 'tags', :action => 'create'} do |f|
  = f.text_field :name
  = f.submit 'Add Tag'